easy_main_test:
    path:     /test/
    defaults: { _controller: EasyMainBundle:Default:test }
    
easy_main_news_show:
    pattern:  /news/{id}/
    defaults: { _controller: EasyMainBundle:Default:newsShow }
    requirements:
        id: \d+
        
easy_main_news:
    path:     /news/
    defaults: { _controller: EasyMainBundle:Default:news }
    
easy_team_all:
    path:     /team/
    defaults: { _controller: EasyMainBundle:Default:teamAll }
    
easy_team_name:
    path:     /team/{name}/
    defaults: { _controller: EasyMainBundle:Default:team }
    
login:
    pattern:   /login/
    defaults:  { _controller: EasyMainBundle:Default:login }
    
login_check:
    pattern:   /login_check/
#    defaults:  { _controller: EasyMainBundle:Default:login }
logout:
    pattern:   /logout
    
easy_main_gallery:
    path:     /gallery/{id}/
    defaults: { _controller: EasyMainBundle:Default:gallery }
    
easy_main_calendar:
    path:     /calendar/{id}/
    defaults: { _controller: EasyMainBundle:Default:calendar }
    
easy_main_easy_times:
    path:     /easytimes/
    defaults: { _controller: EasyMainBundle:Default:easyTimes }
    
easy_main_contacts:
    path:     /contacts/{id}/
    defaults: { _controller: EasyMainBundle:Default:contacts }
    
easy_main_stuff:
    path:     /stuff/{type}/
    defaults: { _controller: EasyMainBundle:Default:stuff }
    
    
form_controller:
    path: /ajax/
    defaults: { _controller: EasyMainBundle:Form:index }
    
    
    
    
    
change_form:
    #pattern: /{_locale}/admin/gd/admin/merchant/get-categories-from-tag/{tagId}
    path: /ajax/test/{type}
    defaults: {_controller: EasyMainBundle:Form:changeForm}
    options:
        expose: true


    

easy_main_controller:
    pattern: /{part1}/
    defaults: { _controller: EasyMainBundle:Default:index}
    
easy_main_controller_part2:
    pattern: /{part1}/{part2}/
    defaults: { _controller: EasyMainBundle:Default:indexPart2}
#    

#easy_main_kid:
#    resource: "@EasyMainBundle/Resources/config/routing/kid.yml"
#    prefix:   /kid
#    
#easy_main_foreign:
#    path:     /foreign/
#    defaults: { _controller: EasyMainBundle:Default:foreign }
#    
#easy_main_summer:
#    resource: "@EasyMainBundle/Resources/config/routing/summer.yml"
#    prefix:   /summer
#    
#easy_main_tsdo:
#    path:     /tsdo/
#    defaults: { _controller: EasyMainBundle:Default:tsdo }
#    
easy_main_homepage:
    path:     /
    defaults: { _controller: EasyMainBundle:Default:main }
    

#    
#    
#
#easy_main_main:
#    path:     /main/
#    defaults: { _controller: EasyMainBundle:Default:main }
#    
