page_tree_up:
    pattern: /admin/page_tree_up/{page_id}
    defaults:  { _controller: EasyMainBundle:Default:up }

page_tree_down:
    pattern: /admin/page_tree_down/{page_id}
    defaults:  { _controller: EasyMainBundle:Default:down }

easy_main_test:
    path:     /test/
    defaults: { _controller: EasyMainBundle:Default:test }
    
easy_main_news_show:
    pattern:  /news/{id}/
    defaults: { _controller: EasyMainBundle:Default:newsShow }
    requirements:
        id: \d+

easy_main_news_archive:
    pattern:  /news/archive/{year}
    defaults: { _controller: EasyMainBundle:Default:newsArchiveShow }
    requirements:
        id: \year+
        
easy_main_news:
    path:     /news/
    defaults: { _controller: EasyMainBundle:Default:news }
    
login:
    pattern:   /login/
    defaults:  { _controller: EasyMainBundle:Default:login }
    
login_check:
    pattern:   /login_check/
#    defaults:  { _controller: EasyMainBundle:Default:login }
logout:
    pattern:   /logout
    
easy_main_gallery:
    path:     /gallery/{id}/
    defaults: { _controller: EasyMainBundle:Default:gallery }

easy_main_linkedgallery:
    path:     /linkedgallery/{id}/
    defaults: { _controller: EasyMainBundle:Default:linkedgallery }

easy_main_calendar_archive:
    pattern:  /calendar/archive/{year}
    defaults: { _controller: EasyMainBundle:Default:calendarArchive }
    requirements:
        id: \year+

easy_main_calendar:
    path:     /calendar/{id}/
    defaults: { _controller: EasyMainBundle:Default:calendar }


    
easy_main_easy_times:
    path:     /easytimes/
    defaults: { _controller: EasyMainBundle:Default:easyTimes }
    
easy_main_contacts:
    path:     /contacts/{id}/
    defaults: { _controller: EasyMainBundle:Default:contacts }
    
easy_main_stuff:
    path:     /stuff{trailingSlash}{type}
    defaults: { _controller: EasyMainBundle:Default:stuff, type: all,trailingSlash : "/" }
    requirements:
        type: .+
        trailingSlash : "[/]{0,1}"

    
form_controller:
    path: /ajax/
    defaults: { _controller: EasyMainBundle:Form:index }
    
    
    
    
    
change_form:
    #pattern: /{_locale}/admin/gd/admin/merchant/get-categories-from-tag/{tagId}
    path: /ajax/test/{type}
    defaults: {_controller: EasyMainBundle:Form:changeForm}
    options:
        expose: true


    

easy_main_controller:
    pattern: /{part1}/
    defaults: { _controller: EasyMainBundle:Default:index}

easy_main_controller_part2:
    pattern: /{part1}/{part2}/
    defaults: { _controller: EasyMainBundle:Default:indexPart2}

#    

#easy_main_kid:
#    resource: "@EasyMainBundle/Resources/config/routing/kid.yml"
#    prefix:   /kid
#    
#easy_main_foreign:
#    path:     /foreign/
#    defaults: { _controller: EasyMainBundle:Default:foreign }
#    
#easy_main_summer:
#    resource: "@EasyMainBundle/Resources/config/routing/summer.yml"
#    prefix:   /summer
#    
#easy_main_tsdo:
#    path:     /tsdo/
#    defaults: { _controller: EasyMainBundle:Default:tsdo }
#    
easy_main_homepage:
    path:     /
    defaults: { _controller: EasyMainBundle:Default:main }
    

#    
#    
#
#easy_main_main:
#    path:     /main/
#    defaults: { _controller: EasyMainBundle:Default:main }
#    

pageNotFound:
    pattern:  /{path}
    defaults: { _controller: EasyMainBundle:Default:pageNotFound, path: '' }
    requirements:
        path: .*