admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
oneup_uploader:
    resource: .
    type: uploader
    methods:  [GET, POST]

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

easy_main:
    resource: "@EasyMainBundle/Resources/config/routing.yml"
    prefix:   /


