Easy\MainBundle\Entity\Calendar:
    type: entity
    table: calendar
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        text:
            type: text
        date:
            type: date
            
    manyToOne:
        media:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            cascade: ["persist"]
            fetch: LAZY
    