Easy\MainBundle\Entity\Content:
    type: entity
    table: content
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            required: false
            nullable: true
        type:
            type: string
        content:
            type: text
            nullable: true
            required: false
        order_column:
            type: integer
            nullable: true
            required: false
            default: 500
        stuff:
            type: string
            nullable: true
            required: false
    manyToOne:
        gallery:
            targetEntity: Application\Sonata\MediaBundle\Entity\Gallery
            joinColumn:
                name: gallery_id
                referencedColumnName: id
        url:
            targetEntity: MainMenu
            joinColumn:
                name: url_id
                referencedColumnName: id
        #media:
         #   targetEntity: Application\Sonata\MediaBundle\Entity\Media
          #  cascade: ["persist"]
           # fetch: LAZY
    oneToMany:
        teams:
            targetEntity: Team
            mappedBy: content
            cascade: ["persist", "remove"] 
            orphanRemoval: true
        contacts:
            targetEntity: Contacts
            mappedBy: content_reference
            cascade: ["persist", "remove"] 
            orphanRemoval: true
