Easy\MainBundle\Entity\Content:
    type: entity
    table: content
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            required: false
            nullable: true
        type:
            type: string
        content:
            type: text
            nullable: true
            required: false
        order_column:
            type: integer
            nullable: true
            required: false
            default: 500
        top_menu:
            type: boolean
            required: false
            nullable: true
        second_menu:
            type: integer
            required: false
            default: 1
            nullable: true
            
    manyToOne:
        gallery:
            targetEntity: Application\Sonata\MediaBundle\Entity\Gallery
            joinColumn:
                name: gallery_id
                referencedColumnName: id
        url:
            targetEntity: MainMenu
            joinColumn:
                name: url_id
                referencedColumnName: id
                
    oneToMany:
        teams:
            targetEntity: Team
            mappedBy: content
            cascade: ["persist", "remove"] 
            orphanRemoval: true
        contacts:
            targetEntity: Contacts
            mappedBy: content_reference
            cascade: ["persist", "remove"] 
            orphanRemoval: true
#            cascade: ["persist", "remove"] 
#            orphanRemoval: true
            
#    oneToMany:
#        team:
#            targetEntity: Team
#            mappedBy: content
#            cascade: ["all"]
#            orphanRemoval: true
#    manyToMany:
#        team:
#          targetEntity: Team
#          joinTable:
#                name: team
#                joinColumns:
#                    content_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    team_id:
#                        referencedColumnName: id
#                        unique: true
#    oneToMany:
#        team:
#            targetEntity: Team
#            mappedBy: content
#    manyToOne:
#        content:
#            targetEntity: Content
#            inversedBy: team
#           
                
                
        
#    oneToMany:
#        inspections:
#            targetEntity: Inspection
#            mappedBy: content
#            cascade: ["all"]
#            orphanRemoval: true
#            
#    manyToOne:
#        images:
#            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            
        