Easy\MainBundle\Entity\MainMenu:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: main_menu
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        title:
            type: string
            length: 255
            nullable: true
        title_menu:
            type: string
            length: 255
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
        url:
            type: string
            length: 255
            nullable: true
        enabled:
            type: boolean
        empty:
            type: boolean
        record:
            type: boolean
        link:
            type: string
            nullable: true
            required: false
        color:
            type: string
            length: 50
        seo_title:
            type: text
        seo_description:
            type: text
        seo_keywords:
            type: text
    manyToOne:
        parent:
            targetEntity: MainMenu
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            nullable: true
            gedmo:
                - treeParent
        city:
            targetEntity: City
            joinColumn:
                name: city_id
                referencedColumnName: id
    oneToMany:
        children:
            targetEntity: MainMenu
            mappedBy: parent
            orderBy:
                lft: ASC
        content:
            targetEntity: Content
            mappedBy: url
