Easy\MainBundle\Entity\News:
    type: entity
    table: news
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
        type:
            type: string
            default: published
        text:
            type: text
        order_column:
            type: integer
        date:
            type: date
        main:
            type: boolean
            default: false
    manyToOne:
        media:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            cascade: ["persist"]
            fetch: LAZY